### ISSUE TITLE
Warnings During Precompile

### ISSUE THREAD

**Issue by kevindirect** [MitchellWeg/MonetDB.jl#22]
I've noticed there were some warnings during precompile (julia version 1.8).

I don't know if this matters here, but I see some duplicate include calls (e.g.  `Mapi.jl` is included three times in the same scope, first in `MonetDB.jl` then also in `MapiExecute.jl` and `Prepare.jl`).

Warnings:
> WARNING: Method definition (::Type{MonetDB.MapiConnectionParams})(Any, Any, Any, Any, Any) in module MonetDB at ~/.julia/packages/MonetDB/S9lKB/src/Mapi.jl:5 overwritten on the same
> line (check for duplicate calls to `include`).
>   ** incremental compilation may be fatally broken for this module **
> 
> WARNING: Method definition (::Type{MonetDB.MapiConnectionParams})(String, String, String, String, Int64) in module MonetDB at ~/.julia/packages/MonetDB/S9lKB/src/Mapi.jl:5 overwritten on the same line (check for duplicate calls to `include`).
>   ** incremental compilation may be fatally broken for this module **
> 
> WARNING: Method definition (::Type{MonetDB.MapiConnectionParams})(Any, Any, Any, Any, Any) in module MonetDB at ~/.julia/packages/MonetDB/S9lKB/src/Mapi.jl:5 overwritten on the same
> line (check for duplicate calls to `include`).
>   ** incremental compilation may be fatally broken for this module **
> 
> WARNING: Method definition (::Type{MonetDB.MapiConnectionParams})(String, String, String, String, Int64) in module MonetDB at ~/.julia/packages/MonetDB/S9lKB/src/Mapi.jl:5 overwritten on the same line (check for duplicate calls to `include`).
>   ** incremental compilation may be fatally broken for this module **
> 
> WARNING: Method definition (::Type{MonetDB.MapiConnection})(Any, Any) in module MonetDB at ~/.julia/packages/MonetDB/S9lKB/src/Mapi.jl:13 overwritten on the same line (check for duplicate calls to `include`).
>   ** incremental compilation may be fatally broken for this module **
> 
> WARNING: Method definition (::Type{MonetDB.MapiConnection})(MonetDB.MapiConnectionParams, Sockets.TCPSocket) in module MonetDB at ~/.julia/packages/MonetDB/S9lKB/src/Mapi.jl:13 overwritten on the same line (check for duplicate calls to `include`).
>   ** incremental compilation may be fatally broken for this module **
> 
> WARNING: Method definition (::Type{MonetDB.MapiConnection})(Any, Any) in module MonetDB at ~/.julia/packages/MonetDB/S9lKB/src/Mapi.jl:13 overwritten on the same line (check for duplicate calls to `include`).
>   ** incremental compilation may be fatally broken for this module **
> 
> WARNING: Method definition (::Type{MonetDB.MapiConnection})(MonetDB.MapiConnectionParams, Sockets.TCPSocket) in module MonetDB at ~/.julia/packages/MonetDB/S9lKB/src/Mapi.jl:13 overwritten on the same line (check for duplicate calls to `include`).
>   ** incremental compilation may be fatally broken for this module **

**Comment by MitchellWeg** [comment]
Hi @kevindirect,

Thank you for showing interest in the project!
Currently this project is in a alpha state, and we're trying to get it production ready asap.
Thanks for reporting issues like this.

Regards,
Mitchell.

**Comment by MitchellWeg** [comment]
> Thanks for your work!
> 
> Yeah, I figured it was early in development.
> 
> Unfortunately I've decided not to use MonetDB for my project (it's a great db, but I realized it's application doesn't match the specific goals for the project). If I was going to use MonetDB in the future, I would definately use this package and help out any way I could with development.
> 
> Best of luck!

Thank you, and I hope to see you back again soon as a regular user!
